//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 12:48:38 AM EDT 
//


package com.avijit.poc.onlinestore.orderbo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineItemNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quntity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unitPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineItemNum",
    "partCd",
    "partName",
    "quntity",
    "unitPrice"
})
@XmlRootElement(name = "lineItem")
public class LineItem {

    @XmlElement(required = true)
    protected String lineItemNum;
    @XmlElement(required = true)
    protected String partCd;
    @XmlElement(required = true)
    protected String partName;
    @XmlElement(required = true)
    protected String quntity;
    @XmlElement(required = true)
    protected String unitPrice;

    /**
     * Gets the value of the lineItemNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineItemNum() {
        return lineItemNum;
    }

    /**
     * Sets the value of the lineItemNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineItemNum(String value) {
        this.lineItemNum = value;
    }

    /**
     * Gets the value of the partCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartCd() {
        return partCd;
    }

    /**
     * Sets the value of the partCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartCd(String value) {
        this.partCd = value;
    }

    /**
     * Gets the value of the partName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartName() {
        return partName;
    }

    /**
     * Sets the value of the partName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartName(String value) {
        this.partName = value;
    }

    /**
     * Gets the value of the quntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuntity() {
        return quntity;
    }

    /**
     * Sets the value of the quntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuntity(String value) {
        this.quntity = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitPrice(String value) {
        this.unitPrice = value;
    }

}
