//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 12:48:38 AM EDT 
//


package com.avijit.poc.onlinestore.orderbo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.avijit.poc.onlinestore.orderbo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.avijit.poc.onlinestore.orderbo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderBilling }
     * 
     */
    public OrderBilling createOrderBilling() {
        return new OrderBilling();
    }

    /**
     * Create an instance of {@link OrderShipping }
     * 
     */
    public OrderShipping createOrderShipping() {
        return new OrderShipping();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link LineItems }
     * 
     */
    public LineItems createLineItems() {
        return new LineItems();
    }

    /**
     * Create an instance of {@link LineItem }
     * 
     */
    public LineItem createLineItem() {
        return new LineItem();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link OrderBilling.PaymentInfo }
     * 
     */
    public OrderBilling.PaymentInfo createOrderBillingPaymentInfo() {
        return new OrderBilling.PaymentInfo();
    }

    /**
     * Create an instance of {@link OrderBilling.Tax }
     * 
     */
    public OrderBilling.Tax createOrderBillingTax() {
        return new OrderBilling.Tax();
    }

    /**
     * Create an instance of {@link OrderBilling.Discount }
     * 
     */
    public OrderBilling.Discount createOrderBillingDiscount() {
        return new OrderBilling.Discount();
    }

    /**
     * Create an instance of {@link OrderShipping.ShippingMethod }
     * 
     */
    public OrderShipping.ShippingMethod createOrderShippingShippingMethod() {
        return new OrderShipping.ShippingMethod();
    }

    /**
     * Create an instance of {@link Orders }
     * 
     */
    public Orders createOrders() {
        return new Orders();
    }

}
